---

Original : False

Transformer_Original : 
  _target_ : training.TransformerNetwork
  use_original_robotic_platform : True
  train_step_counter : 0
  vocab_size : 256
  token_embedding_size : 512
  num_layers : 1
  layer_size : 4096
  num_heads : 8
  feed_forward_size : 512
  dropout_rate : 0.1
  time_sequence_length : 6
  crop_size : 256
  use_token_learner : True
  return_attention_scores : False
  params_dict :
      image_channels : 3
      image_height : 200
      image_width : 200
      image_space_low : 0.0
      image_space_high : 1.0
      world_vector_space_shape : 3
      world_vector_space_low : -1.0
      world_vector_space_high : 1.0
      rotation_delta_space_shape : 3
      rotation_delta_space_low : -3.14
      rotation_delta_space_high : 3.14
      gripper_closedness_space_shape : 1
      gripper_closedness_space_low : -1.0
      gripper_closedness_space_high : 1.0
   
Transformer_MIVIA : 
  _target_ : training.TransformerNetwork
  use_original_robotic_platform : False
  train_step_counter : 0
  vocab_size : 256
  token_embedding_size : 512
  num_layers : 1
  layer_size : 4096
  num_heads : 8
  feed_forward_size : 512
  dropout_rate : 0.1
  time_sequence_length : 6
  crop_size : 256
  use_token_learner : True
  return_attention_scores : False
  params_dict :
      image_channels : 3
      image_height : 200
      image_width : 200
      image_space_low : 0.0
      image_space_high : 1.0
      world_vector_space_shape : 3
      world_vector_space_low : -1.0
      world_vector_space_high : 1.0
      rotation_delta_space_shape : 3
      rotation_delta_space_low : -6.28
      rotation_delta_space_high : 6.28
      gripper_closedness_space_shape : 2

rt1_dataset:
    _target_ : training.CustomDataset
    data_path : "/mnt/localstorage/mspremulli/RT-1_Converted_Dataset/"
    time_sequence_length : 6
    discard_length : 12

mivia_simulated_dataset:
    _target_ : training.CustomDataset
    data_path : "/user/mspremulli/Language-Conditioned-IL/data/converted_simulated_ur5e_delta/"
    time_sequence_length : 6
    discard_length : 12

training:
   epochs : 90
   batch_size : 32
   num_workers : 8
   checkpoint : 5
   checkpoint_save_path : "/user/mspremulli/Language-Conditioned-IL/rt-1_simulated_checkpoints_no_pretraining/"
   load_pretraining : False
   checkpoint_pretraining : "/user/mspremulli/Language-Conditioned-IL/rt1_checkpoints/rt-1_pretraining_checkpoint_epoch_8_loss_101.1661436528666_batch_32"
  
 